version: "2"
linters:
  enable:
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - goconst
    - gocritic
    - gosec
    - ireturn
    - mnd
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - tagalign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: could not import github.com/sstallion/go-hid
      - path: (.+)\.go$
        text: 'undefined: hid'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
