---
output:
  show-stats: true
  sort-results: true
issues:
  exclude:
    # go-hid needs to be built for the platform specifically
    - "could not import github.com/sstallion/go-hid"
    - "undefined: hid"
  fix: true
  max-same-issues: 10
linters:
  enable:
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - ireturn
    - mnd
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - tagalign
