GO := "go"
GOFLAGS := ""
PLUGIN := "ca.michaelabon.logitechlitra.sdPlugin"
INSTALLDIR := "$HOME/Library/Application Support/com.elgato.StreamDeck/Plugins/{{ PLUGIN }}"

build: streamdeck-logitech-litra

streamdeck-logitech-litra:
    {{ GO }} build {{ GOFLAGS }} -o streamdeck-logitech-litra main.go

[macos]
link:
    ln -s \
        "{{ justfile_directory() }}" \
        "$HOME/Library/Application Support/com.elgato.StreamDeck/Plugins"

[windows]
link:
    mklink /D "%AppData%\Elgato\StreamDeck\Plugins\{{ PLUGIN }}" "{{ justfile_directory() }}"
